apiVersion: v1
kind: Service
metadata:
  name: doglib-service
  labels:
    app: doglib
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: doglib
    tier: frontend
